/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ethicsassignementpeace;

import javax.swing.JOptionPane;

/**
 *
 * @author luayon
 */
public class GamePlay2 extends javax.swing.JFrame {

    private int points = 0;
    private int levelCounter = 0;

    /**
     * Creates new form GamePlay2
     */
    public GamePlay2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CoverBar = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        LevelLabel = new javax.swing.JLabel();
        ScenarioLabel = new javax.swing.JLabel();
        ScenarioHappeningLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BackgroundPicture = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LevelLabel1 = new javax.swing.JLabel();
        ScenarioLabel1 = new javax.swing.JLabel();
        ScenarioHappeningLabel1 = new javax.swing.JLabel();
        PeacePointsLabel = new javax.swing.JLabel();
        ButtonC = new javax.swing.JButton();
        ButtonA = new javax.swing.JButton();
        ButtonB = new javax.swing.JButton();
        BackgroundPicture1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CoverBar.setBackground(new java.awt.Color(113, 59, 45));
        getContentPane().add(CoverBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 1150, 49));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LevelLabel.setFont(new java.awt.Font("Press Start 2P", 0, 24)); // NOI18N
        LevelLabel.setForeground(new java.awt.Color(255, 255, 255));
        LevelLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(LevelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 90, 40));

        ScenarioLabel.setFont(new java.awt.Font("RetroPix", 1, 24)); // NOI18N
        ScenarioLabel.setForeground(new java.awt.Color(255, 255, 255));
        ScenarioLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(ScenarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 270, 40));

        ScenarioHappeningLabel.setFont(new java.awt.Font("RetroPix", 0, 24)); // NOI18N
        jPanel1.add(ScenarioHappeningLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 840, 240));

        jButton1.setBackground(new java.awt.Color(244, 96, 101));
        jButton1.setFont(new java.awt.Font("Press Start 2P", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("START");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 150, 60));

        BackgroundPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURES/10.gif"))); // NOI18N
        jPanel1.add(BackgroundPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 648));

        jTabbedPane1.addTab("tab1", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LevelLabel1.setFont(new java.awt.Font("Press Start 2P", 0, 24)); // NOI18N
        LevelLabel1.setForeground(new java.awt.Color(255, 255, 255));
        LevelLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(LevelLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 90, 40));

        ScenarioLabel1.setFont(new java.awt.Font("RetroPix", 1, 20)); // NOI18N
        ScenarioLabel1.setForeground(new java.awt.Color(255, 255, 255));
        ScenarioLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(ScenarioLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 270, 40));

        ScenarioHappeningLabel1.setFont(new java.awt.Font("RetroPix", 0, 24)); // NOI18N
        jPanel2.add(ScenarioHappeningLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 840, 240));

        PeacePointsLabel.setFont(new java.awt.Font("RetroPix", 1, 36)); // NOI18N
        PeacePointsLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(PeacePointsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 580, 70, 30));

        ButtonC.setBackground(new java.awt.Color(244, 96, 101));
        ButtonC.setFont(new java.awt.Font("Press Start 2P", 0, 10)); // NOI18N
        ButtonC.setForeground(new java.awt.Color(255, 255, 255));
        ButtonC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonC, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 510, 40));

        ButtonA.setBackground(new java.awt.Color(244, 96, 101));
        ButtonA.setFont(new java.awt.Font("Press Start 2P", 0, 10)); // NOI18N
        ButtonA.setForeground(new java.awt.Color(255, 255, 255));
        ButtonA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonA, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 510, 40));

        ButtonB.setBackground(new java.awt.Color(244, 96, 101));
        ButtonB.setFont(new java.awt.Font("Press Start 2P", 0, 10)); // NOI18N
        ButtonB.setForeground(new java.awt.Color(255, 255, 255));
        ButtonB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonB, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 510, 40));

        BackgroundPicture1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURES/10.gif"))); // NOI18N
        jPanel2.add(BackgroundPicture1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 648));

        jTabbedPane1.addTab("tab2", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1152, 648));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // Start the game and initialize the first level
        levelCounter = 0;
        points = 0;
        PeacePointsLabel.setText(" " + points);
        nextLevel();
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCActionPerformed
        // TODO add your handling code here:
        evaluateChoice("C");

    }//GEN-LAST:event_ButtonCActionPerformed

    private void ButtonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAActionPerformed
        // TODO add your handling code here:
        evaluateChoice("A");
    }//GEN-LAST:event_ButtonAActionPerformed

    private void ButtonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBActionPerformed
        // TODO add your handling code here:
        evaluateChoice("B");
    }//GEN-LAST:event_ButtonBActionPerformed
    private void nextLevel() {
        if (levelCounter >= 10) {
            WinMenu winMenu = new WinMenu();
            winMenu.setScore(points);
            winMenu.setVisible(true);
            this.dispose(); // Close the current window
        }

        String[] levels = {
            "SCHOOL CONFLICT",
            "COMMUNITY DISPUT",
            "ONLINE CONFLICT",
            "WORKPLACE DISAGREEMENT",
            "FAMILY ARGUMENT",
            "PUBLIC DISPUTE",
            "SPORTS CONFLICT",
            "CULTURAL MISUNDERSTANDING",
            "POLITICAL DEBATE",
            "ENVIRONMENTAL DISPUTE"
        };

        String[] scenarios = {
            "You are at school, and you notice two students having a heated argument in the hallway. They are shouting at each other and seem on the verge of a physical fight. Other students are starting to gather around, making the situation more intense.",
            "During a community event, you hear your neighbors arguing loudly about a noisy party that went on late into the night. One neighbor is angry about the disturbance, while the other feels they have the right to enjoy their property. The argument is starting to attract attention from other community members.",
            "You are part of an online community and notice two members getting into a heated debate about a sensitive topic. The argument is escalating, with personal attacks being thrown back and forth. Other community members are joining in, making the situation more chaotic.",
            "At work, you witness two colleagues arguing about the best way to handle a project. One person is getting visibly upset, and their voices are rising. The disagreement is starting to disrupt the entire office.",
            "You are at a family gathering, and two relatives start arguing about a long-standing issue. The argument is getting louder and more personal, making other family members uncomfortable and worried about a potential fight.",
            "While in a public place, you see two strangers arguing about who was first in line. The argument is becoming more aggressive, and people around them are starting to feel uneasy.",
            "During a sports event, you see two players from opposing teams arguing about a foul play. The argument is getting intense, and other players are getting involved, increasing the tension on the field.",
            "You witness a cultural misunderstanding at an event where someone unintentionally offends another person. The offended person is angry and confronts the other, causing a scene in front of everyone.",
            "You are watching a political debate where two candidates are arguing about their policies. The debate is getting personal and heated, with both sides refusing to back down.",
            "During an environmental protest, two groups are arguing about the best approach to tackling climate change. The argument is becoming more intense, with accusations and harsh words being exchanged."
        };

        String[][] choices = {
            {"Suggest a compromise that benefits everyone.", "Ignore the argument.", "Take sides and argue."},
            {"Offer to mediate a discussion between them.", "Walk away and avoid the situation.", "Yell at them to stop arguing."},
            {"Suggest they discuss the topic privately.", "Scroll past and ignore the conflict.", "Join the argument and take a side."},
            {"Propose a meeting to discuss the project calmly.", "Pretend you didn't see anything.", "Support one colleague's argument."},
            {"Encourage them to talk it out peacefully.", "Stay silent and avoid involvement.", "Fuel the argument with more opinions."},
            {"Calmly suggest they take turns explaining their sides.", "Stay out of it and leave the area.", "Intervene aggressively to stop the fight."},
            {"Encourage fair play and mutual respect.", "Ignore the conflict and focus on the game.", "Instigate more conflict between the players."},
            {"Explain the cultural differences calmly.", "Avoid getting involved in the argument.", "Blame one side for the misunderstanding."},
            {"Promote a respectful and factual discussion.", "Turn off the debate and do something else.", "Support one candidate aggressively."},
            {"Encourage collaboration and mutual understanding.", "Ignore the groups and leave the protest.", "Criticize one group for their approach."}
        };

        String[][] tips = {
            {"Finding common ground helps resolve conflicts.", "Ignoring the problem won't make it go away.", "Taking sides can escalate the conflict."},
            {"Mediation can help both sides find a solution.", "Avoiding the issue won't resolve the conflict.", "Yelling can escalate the situation."},
            {"Private discussions can prevent public conflicts.", "Ignoring online conflicts won't make them disappear.", "Joining the argument can increase hostility."},
            {"Calm discussions can lead to better solutions.", "Ignoring workplace conflicts won't solve them.", "Taking sides can create office tension."},
            {"Encouraging peaceful discussions can resolve issues.", "Avoiding family conflicts won't help.", "Fueling arguments can harm relationships."},
            {"Taking turns can prevent arguments from escalating.", "Avoiding conflicts won't resolve them.", "Aggression can make conflicts worse."},
            {"Encouraging respect promotes fair play.", "Ignoring conflicts won't resolve them.", "Instigating conflicts can ruin the game."},
            {"Calm explanations can resolve misunderstandings.", "Avoiding conflicts won't help resolve them.", "Blaming can escalate conflicts."},
            {"Respectful discussions can lead to better understanding.", "Ignoring debates won't make issues disappear.", "Aggressive support can fuel conflicts."},
            {"Collaboration can help find common solutions.", "Ignoring conflicts won't resolve them.", "Criticizing can increase tension."}
        };

        LevelLabel1.setText("" + (levelCounter + 1));
        ScenarioLabel1.setText(levels[levelCounter]);
        ScenarioHappeningLabel1.setText("<html>" + scenarios[levelCounter] + "<html>");
        ButtonA.setText("<html>" + choices[levelCounter][0] + "<html>");
        ButtonB.setText("<html>" + choices[levelCounter][1] + "<html>");
        ButtonC.setText("<html>" + choices[levelCounter][2] + "<html>");

        levelCounter++;
    }

    private void evaluateChoice(String choice) {
        String[][] correctChoices = {
            {"A", "Finding common ground helps resolve conflicts."},
            {"A", "Mediation can help both sides find a solution."},
            {"A", "Private discussions can prevent public conflicts."},
            {"A", "Calm discussions can lead to better solutions."},
            {"A", "Encouraging peaceful discussions can resolve issues."},
            {"A", "Taking turns can prevent arguments from escalating."},
            {"A", "Encouraging respect promotes fair play."},
            {"A", "Calm explanations can resolve misunderstandings."},
            {"A", "Respectful discussions can lead to better understanding."},
            {"A", "Collaboration can help find common solutions."}
        };

        String correctChoice = correctChoices[levelCounter - 1][0];
        String tip = correctChoices[levelCounter - 1][1];

        if (choice.equalsIgnoreCase(correctChoice)) {
            points += 10;
            JOptionPane.showMessageDialog(this, "Correct! " + tip + " (+10 points)");
        } else if (choice.equalsIgnoreCase("B")) {
            points -= 10;
            JOptionPane.showMessageDialog(this, "Neutral. Ignoring doesn't solve the conflict. (-10 points)");
        } else {
            points -= 10;
            JOptionPane.showMessageDialog(this, "Incorrect. Escalating conflict is not the answer. (-10 points)");
        }

        PeacePointsLabel.setText(" " + points);
        
        if (points <= 0) {
            endGame();
        } else {
            nextLevel();
        }
    }

    private void endGame() {
        LoseMenu loseMenu = new LoseMenu();
        loseMenu.setScore(points);
        loseMenu.setVisible(true);
        this.dispose(); // Close the current window
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GamePlay2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GamePlay2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GamePlay2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamePlay2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GamePlay2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundPicture;
    private javax.swing.JLabel BackgroundPicture1;
    private javax.swing.JButton ButtonA;
    private javax.swing.JButton ButtonB;
    private javax.swing.JButton ButtonC;
    private javax.swing.JPanel CoverBar;
    private javax.swing.JLabel LevelLabel;
    private javax.swing.JLabel LevelLabel1;
    private javax.swing.JLabel PeacePointsLabel;
    private javax.swing.JLabel ScenarioHappeningLabel;
    private javax.swing.JLabel ScenarioHappeningLabel1;
    private javax.swing.JLabel ScenarioLabel;
    private javax.swing.JLabel ScenarioLabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
