/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ethicsassignementpeace;

/**
 *
 * @author luayon
 */
public class WinMenu extends javax.swing.JFrame {

    // Declare the label to show score if it's not already defined
    /**
     * Creates new form Start
     */
    public WinMenu() {
        initComponents();
        ScoreLabel.setText("");
        
    }

    public void setScore(int points) {
        ScoreLabel.setText("" + points);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CoverBar = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        NextButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        NextButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        NextButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        NextButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        NextButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        NextButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        NextButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        NextButton7 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        PlayAgainButton1 = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        ScoreLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CoverBar.setBackground(new java.awt.Color(113, 59, 45));
        getContentPane().add(CoverBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 1150, 40));

        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NextButton.setContentAreaFilled(false);
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });
        jPanel3.add(NextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 210, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURES/11.gif"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1152, 648));

        jTabbedPane2.addTab("tab1", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NextButton1.setContentAreaFilled(false);
        NextButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(NextButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 210, 30, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURES/12.gif"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1152, 648));

        jTabbedPane2.addTab("tab2", jPanel4);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NextButton2.setContentAreaFilled(false);
        NextButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(NextButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 210, 30, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURES/13.gif"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1152, 648));

        jTabbedPane2.addTab("tab3", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NextButton3.setContentAreaFilled(false);
        NextButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(NextButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 210, 30, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURES/14.gif"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1152, 648));

        jTabbedPane2.addTab("tab4", jPanel2);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NextButton4.setContentAreaFilled(false);
        NextButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(NextButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 210, 30, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURES/15.gif"))); // NOI18N
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1152, 648));

        jTabbedPane2.addTab("tab5", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NextButton5.setContentAreaFilled(false);
        NextButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButton5ActionPerformed(evt);
            }
        });
        jPanel6.add(NextButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 210, 30, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURES/16.gif"))); // NOI18N
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1152, 648));

        jTabbedPane2.addTab("tab6", jPanel6);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NextButton6.setContentAreaFilled(false);
        NextButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButton6ActionPerformed(evt);
            }
        });
        jPanel7.add(NextButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 210, 30, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURES/17.gif"))); // NOI18N
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1152, 648));

        jTabbedPane2.addTab("tab7", jPanel7);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NextButton7.setContentAreaFilled(false);
        NextButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButton7ActionPerformed(evt);
            }
        });
        jPanel8.add(NextButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 210, 30, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURES/18.gif"))); // NOI18N
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1152, 648));

        jTabbedPane2.addTab("tab8", jPanel8);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PlayAgainButton1.setContentAreaFilled(false);
        PlayAgainButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayAgainButton1ActionPerformed(evt);
            }
        });
        jPanel9.add(PlayAgainButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 180, 60));

        ExitButton.setContentAreaFilled(false);
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        jPanel9.add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, 180, 60));

        ScoreLabel.setFont(new java.awt.Font("RetroPix", 0, 30)); // NOI18N
        ScoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ScoreLabel.setText("0");
        jPanel9.add(ScoreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, 40, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURES/21.gif"))); // NOI18N
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1152, 648));

        jTabbedPane2.addTab("tab9", jPanel9);

        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1152, 648));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NextButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButton3ActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(4);

    }//GEN-LAST:event_NextButton3ActionPerformed

    private void NextButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButton2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(3);
    }//GEN-LAST:event_NextButton2ActionPerformed

    private void NextButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButton1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(2);
    }//GEN-LAST:event_NextButton1ActionPerformed

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(1);
    }//GEN-LAST:event_NextButtonActionPerformed

    private void NextButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButton4ActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(5);
    }//GEN-LAST:event_NextButton4ActionPerformed

    private void NextButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButton5ActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(6);
    }//GEN-LAST:event_NextButton5ActionPerformed

    private void NextButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButton6ActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(7);
    }//GEN-LAST:event_NextButton6ActionPerformed

    private void NextButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButton7ActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(8);
    }//GEN-LAST:event_NextButton7ActionPerformed

    private void PlayAgainButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayAgainButton1ActionPerformed
        // TODO add your handling code here:
        Start startGame = new Start();
        startGame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PlayAgainButton1ActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CoverBar;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton NextButton;
    private javax.swing.JButton NextButton1;
    private javax.swing.JButton NextButton2;
    private javax.swing.JButton NextButton3;
    private javax.swing.JButton NextButton4;
    private javax.swing.JButton NextButton5;
    private javax.swing.JButton NextButton6;
    private javax.swing.JButton NextButton7;
    private javax.swing.JButton PlayAgainButton1;
    private javax.swing.JLabel ScoreLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
